import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LiveWithCodeAnkit",
  description: "Generated by LiveWithCodeAnkit",
  openGraph: {
    title: "LiveWithCodeAnkit",
    description: "Generated by LiveWithCodeAnkit",
    url: "https://github.com/LiveWithCodeAnkit",
    siteName: "LiveWithCodeAnkit",
    locale: "en_US",
    type: "website",
  },
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
